name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dependances
        working-directory: starter-app
        run: pip install -r requirements.txt

      - name: Verifier le style avec flake8
        working-directory: starter-app
        run: flake8 . --max-line-length=100 --exclude=.venv

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installer les dependances
        working-directory: starter-app
        run: pip install -r requirements.txt

      - name: Lancer les tests
        working-directory: starter-app
        run: pytest


  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construire et pousser l'image
        uses: docker/build-push-action@v6
        with:
          context: ./starter-app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/atelier-devops-web:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/atelier-devops-web:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
      
      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Rendre le script executable
        run: chmod +x deploy/deploy.sh

      - name: deploy app
        run: ./deploy/deploy.sh
